# Generated by Django 2.0.4 on 2018-05-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inference', '0002_fact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expression',
            name='operator',
            field=models.CharField(choices=[('EQUAL', '='), ('NOT EQUAL', '!=')], max_length=10),
        ),
    ]
