# Generated by Django 2.0.4 on 2018-05-03 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=20)),
                ('operator', models.CharField(choices=[('EQUAL', '='), ('NOT EQUAL', '!=')], max_length=2)),
                ('value', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consequent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consequent', to='inference.Expression')),
                ('expressions', models.ManyToManyField(to='inference.Expression', verbose_name='antecedents')),
            ],
        ),
    ]
