# Generated by Django 2.0.4 on 2018-05-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inference', '0003_auto_20180505_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expression',
            name='operator',
        ),
        migrations.AlterField(
            model_name='expression',
            name='attribute',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='expression',
            name='value',
            field=models.BooleanField(),
        ),
    ]
